#!/usr/bin/env bash
#kubeadm cluster bootstrap library: lima VM lifecycle + kubeadm/Cilium/registry wiring.
#Pure data always comes from scripts/lib/kubeadm_profile.py (single source of truth). This file is only used as glue.
#
#Lima 2.2.0 Note (Task 1 spike conclusion, do not change based on intuition from other versions):
#- no `limactl exec`: always `limactl shell <vm> --` (sudo/env injection/herdoc
#stdin/exit code transparent transmission has been verified by spike).
#- The creation of the named user-v2 network `kube` is not idempotent: first check for duplication with `limactl network ls` and then create it.
#- The host has no 192.168.6.x direct route: API server/registry can only pass through CP
#portForwards (6443→1844x, 5000→151xx) access.
#- Change the server of kubeconfig to https://127.0.0.1:<api-port> and
#--tls-server-name=<CP static IP>: kubeadm certificate SAN is advertise-address,
#Does not contain 127.0.0.1.
#- Cluster-level portForwards only exist in the yaml of the CP (vms[0]) from which the api port is read.
#
#Semantic convention (for consumption by Task 6/7):
#kb_vm_down = stop and save disk (`limactl stop`), kb_vm_up can be pulled up as is, kubeadm status
#Reserved; completely delete the VM with kb_vm_delete / kb_prune.
#
#This file is used by source to impose `set -euo pipefail` on the calling shell.
set -euo pipefail

kb_repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
kb_infra_root="${KB_INFRA_ROOT:-$kb_repo_root}"
kb_profile_script="${KB_PROFILE_SCRIPT:-$kb_repo_root/scripts/lib/kubeadm_profile.py}"
KB_KUBEADM_K8S_VERSION="${KB_KUBEADM_K8S_VERSION:-v1.36.1}"

kb_profile() { python3 "$kb_profile_script" "$@"; }
kb_log() { printf '[kb] %s\n' "$*" >&2; }

# ---------------------------------------------------------------------------
#profile data access (single source of truth: kubeadm_profile.py CLI and its rendering products)
# ---------------------------------------------------------------------------

#The one host state directory ($INFRA_DIR, default $kb_repo_root/.state). Everything written on
#the host lives under it: kubeconfigs, the Argo CD manifest cache, the Helm cache, node pool
#event logs. common.sh takes $infra_dir from here, so the two can no longer name different
#directories -- they used to, and `make bootstrap` chmod-ed a file nothing had created.
kb_state_dir() { printf '%s\n' "${INFRA_DIR:-$kb_repo_root/.state}"; }

#kubeconfig host absolute path ($INFRA_DIR/kubeconfig-<cluster>).
kb_kubeconfig_path() {
  local name
  #The profile contributes the file name only. An unknown cluster makes it exit non-zero, but
  #the exit status of a pipeline is sed's, so without this check the caller silently receives
  #the state directory with a trailing slash and chmod/kubectl fail somewhere far away.
  name="$(kb_profile show "$1" | sed -n 's/.*kubeconfig=//p')"
  if [ -z "$name" ]; then
    echo "no kubeconfig name for cluster: $1" >&2
    return 1
  fi
  printf '%s/%s\n' "$(kb_state_dir)" "$name"
}

#Static IP of the first VM (= CP, vms[0]).
kb_cluster_ip() { kb_profile show "$1" | sed -n "s/.*ips=\['\([^']*\)'.*/\1/p"; }

#Specify the static IP of the VM (single VM version of kb_cluster_ip).
kb_vm_ip() { kb_profile ip-of "$1" "$2"; }

#Static IPs for all VMs in the cluster, separated by spaces (multi-node version of kb_cluster_ip). Across clusters
#NetworkPolicy's /32 whitelist must use it: NodePort traffic source IP, from the cluster's
#Which node comes in is the address of that node - if only CP is released, after adding workers, it will fall
#All consumer pods on the worker timed out silently (tested on 2026-08-18 when two nodes were disassembled in the workload).
#[critical] If it cannot be parsed, it must fail on the spot and cannot return an empty string. The caller is all `for ip in $ips` and
#"Generate whitelist node by node" in two forms, no error will be reported if the empty list is empty: verify.sh's four peer-access
#The assertion collective has zero cycles and all green passes, and the whitelist generated by ensure_*_peer_access only remains
#The hidden, cross-cluster connection of 127.0.0.1 was completely lost by Cilium. Both consequences are silent, compared to
#"The content of the whitelist is incorrect" is much harder to check - the latter at least verify will be red.
kb_cluster_ips() {
  local ips
  ips="$(kb_profile show "$1" | sed -n "s/.*ips=\[\(.*\)\].*/\1/p" | tr -d "',")"
  if [ -z "$ips" ]; then
    kb_log "kb_cluster_ips: failed to parse ips for $1 (did kubeadm_profile.py show output format change?)"
    return 1
  fi
  printf '%s\n' "$ips"
}

#The endpoint IP of selected workload cross-cluster bridge = the static IP of "the node that actually hosts the selected workload pod".
#Why can't you refer to CP:selected workload's NodePort externalTrafficPolicy: Local - Bridge
#External traffic after DNAT will be discarded if it hits a node without a local endpoint, and the pod will only fall to the worker.
#Refers to CP as the silent timeout (2026-08-17 actual measurement .11:30081 unreachable / .12:30081 200).
#Why not use node InternalIP: kubelet currently reports the DHCP secondary address of eth0
#(The segment is not reserved, leases.json may drift after being reset), the bridge must be nailed to the netplan static segment.
#Nodes are deduced in real time by kubectl (the bridge follows the pod: worker/selected workload will be added in the future)
# Node, make bootstrap replays this function to converge); the pod cannot be found (not deployed/not started). The bottom line is
#"The first non-CP VM". Single copy assumption: When there are multiple copies and span nodes, Local semantics need to be node-by-node.
#Endpoint, here only items[0] is taken.
#The static IP of the "node hosting a certain pod". The above reason is useful for all "must hit the actual location of the pod"
#The wiring of "node" is established, not only the selected workload-CP is tainted, the workload only falls on the worker, which refers to the CP
#It just fails silently.
kb_pod_node_ip() {
  local cluster="${1:?kb_pod_node_ip: cluster}"
  local namespace="${2:?kb_pod_node_ip: namespace}"
  local selector="${3:?kb_pod_node_ip: selector}"
  local kubeconfig node vm
  kubeconfig="$(kb_kubeconfig_path "$cluster")"
  if [ -s "$kubeconfig" ]; then
    node="$(kubectl --kubeconfig "$kubeconfig" -n "$namespace" \
      get pod -l "$selector" \
      -o jsonpath='{.items[0].spec.nodeName}' 2>/dev/null || true)"
  fi
 # k8s node name = lima-<vm name> (kubeadm join uses hostname), strip the prefix back to the VM name;
 # The derivation fails or the node is not in the VM list of this cluster → Find the first non-CP VM (vms[1]).
  vm="${node#lima-}"
  if [ -z "$node" ] \
    || ! kb_cluster_vms "$cluster" | tr ' ' '\n' | grep -Fxq "$vm"; then
    vm="$(kb_cluster_vms "$cluster" | awk '{print $2}')"
  fi
  [ -n "$vm" ] || return 1
  kb_vm_ip "$cluster" "$vm"
}

#All VM names in the cluster (space separated).
kb_cluster_vms() { kb_profile show "$1" | sed -n 's/.*vms=\([^ ]*\).*/\1/p' | tr ',' ' '; }

#API server's host forwarding port: profile does not directly output port_forwards, which is rendered from Task 3
#Get the hostPort corresponding to guestPort 6443 from the CP yaml (infra/lima/<cp>.yaml) - the same source data,
#Don't drop per-cluster literals in bash.
kb_api_port() {
  local cp yml
  cp="$(kb_cluster_vms "$1" | awk '{print $1}')"
  yml="$kb_infra_root/lima/${cp}.yaml"
  [[ -s "$yml" ]] || { echo "missing lima yaml: $yml" >&2; return 1; }
  awk '
    /^portForwards:/ { pf = 1; next }
    pf && /guestPort: 6443$/ { hit = 1; next }
    hit && /hostPort:/ { print $2; exit }
    pf && /^[^ \t]/ { pf = 0 }
  ' "$yml"
}

# ---------------------------------------------------------------------------
#VM life cycle
# ---------------------------------------------------------------------------

#[critical] You cannot use grep -q: it will exit on hit and cause the upstream limactl to eat SIGPIPE(141).
#Under set -o pipefail, "existence" is misjudged as "does not exist" (actual test preflight/destroy stable recovery
#now). grep without -q will read all the input and then exit, which is semantically equivalent and has no race conditions.
kb_vm_exists() { limactl list -f '{{.Name}}' 2>/dev/null | grep -Fx "$1" >/dev/null; }

kb_vm_state() { limactl list -f '{{.Name}} {{.Status}}' 2>/dev/null | awk -v v="$1" '$1 == v { print $2 }'; }

kb_vm_up() {
  local vm="$1" yml="$kb_infra_root/lima/${1}.yaml"
  [[ -s "$yml" ]] || { echo "missing lima yaml: $yml" >&2; return 1; }
  if kb_vm_exists "$vm"; then
    if [[ "$(kb_vm_state "$vm")" == "Running" ]]; then
      kb_log "vm $vm already running"
      return 0
    fi
 # Existing instances (including reuse after kb_vm_down): directly pull up by name, and the disk/kubeadm status is retained.
    limactl start --timeout 20m0s "$vm"
    return 0
  fi
 # First build: Create and start from yaml. First boot image download + cloud-init (containerd/kubeadm
 #Install + netplan static IP), give sufficient timeout; when provision fails, start will exit with non-zero value.
 # Check /var/log/cloud-init-output.log in guest.
  limactl start --timeout 30m0s --name "$vm" "$yml"
}

#Save the disk during shutdown: VM and data are retained and can be pulled up as they are using kb_vm_up (the cluster will not be re-inited).
kb_vm_down() {
  local vm="$1"
  if ! kb_vm_exists "$vm"; then
    echo "vm absent: $vm" >&2
    return 0
  fi
  if [[ "$(kb_vm_state "$vm")" == "Stopped" ]]; then
    kb_log "vm $vm already stopped"
    return 0
  fi
  limactl stop "$vm"
}

#Completely deleted (irreversible). Use this or kb_prune for e2e/cleanup scenarios, don't use kb_vm_down.
kb_vm_delete() {
  local vm="$1"
  if ! kb_vm_exists "$vm"; then
    echo "vm absent: $vm" >&2
    return 0
  fi
  limactl delete -f "$vm"
}

#Lima 2.2.0 does not have `limactl exec`; `--` will then transparently transmit the entire string to the guest.
kb_root() { local vm="$1"; shift; limactl shell "$vm" -- sudo "$@"; }

# ---------------------------------------------------------------------------
#Network (rule 0: `limactl network create` is not idempotent, check first and then build)
# ---------------------------------------------------------------------------

#The leases file guarded by kube. Daemon lazily starts (the first VM attached to the network) and reads its seeds --leases,
#Therefore, pre-writing before building the network = the guard is born with a reserved segment (2026-08-17 kbtest experiment + running guard
#The --leases are double empirically consistent with the documentation verbatim). network create only registers network unclear files.
kb_network_dir() { printf '%s/_networks/kube\n' "${LIMA_HOME:-$HOME/.lima}"; }
kb_network_leases_file() { printf '%s/leases.json\n' "$(kb_network_dir)"; }
kb_network_endpoint() { printf '%s/kube_ep.sock\n' "$(kb_network_dir)"; }

#Write DHCP reserved segments (kubeadm_profile.DHCP_RESERVED_RANGES) into leases.json.
#It only affects the next startup of the daemon; to take effect immediately on a running daemon, use kb_flood_dhcp_reservations.
kb_ensure_dhcp_reservations() {
  local f added
  f="$(kb_network_leases_file)"
  added="$(kb_profile reserve-dhcp --file "$f")"
  if [[ "$added" != "0" ]]; then
    kb_log "dhcp reservations: +$added entries -> $f (seeded on next daemon start)"
  fi
}

#The running kube daemon does not hot load leases.json, nor does it have a lease mutation API. Equivalent:
#Send a naked DHCP DISCOVER with synthesized MAC from any VM connected to the network, and keep the free address of [1..reserve the upper bound]
#Occupy the space one by one (Task 7b §4.1 Actual test: DISCOVER means accounting, OFFER means the unclaimed lease is still there).
#The reserved entries of MAC and leases.json are derived from the same source, and both sides converge to the same table. Idempotent: already occupied
#No packages are sent at this time. After the daemon is restarted, it will be seeded by leases.json and there is no need to rerun it.
#Usage: kb_flood_dhcp_reservations <vm> [iface] # vm = any running VM hanging on the kube network
kb_flood_dhcp_reservations() {
  local vm="$1" iface="${2:-eth0}" ep tmp macs count
  ep="$(kb_network_endpoint)"
  if ! kb_vm_exists "$vm"; then
    echo "vm absent: $vm (need a running kube-attached vm to flood)" >&2
    return 1
  fi
  if [[ ! -S "$ep" ]]; then
    kb_log "no running kube usernet daemon ($ep); leases.json covers next daemon start"
    return 0
  fi
  tmp="$(mktemp)"
  curl -fsS --unix-socket "$ep" http://localhost/leases >"$tmp"
  macs="$(kb_profile flood-plan --live "$tmp")"
  rm -f "$tmp"
  count="$(printf '%s' "$macs" | grep -c . || true)"
  if (( count == 0 )); then
    kb_log "dhcp reservations already hold the live pool; nothing to flood"
    return 0
  fi
  kb_log "flooding $count dhcp slots via $vm:$iface (raw DISCOVER, ~$((count * 2 / 3))s)"
 # The MAC list is passed to guest via argv (no blanks, safe word segmentation); the script body is passed to stdin.
  # shellcheck disable=SC2086
  limactl shell "$vm" -- sudo python3 - "$iface" $macs <<'FLOOD'
import socket, struct, sys, time

iface, macs = sys.argv[1], [m.replace(":", "") for m in sys.argv[2:]]

def checksum(data):
    if len(data) % 2:
        data += b"\0"
    s = sum(struct.unpack("!%dH" % (len(data) // 2), data))
    s = (s >> 16) + (s & 0xFFFF)
    s += s >> 16
    return (~s) & 0xFFFF

def discover(mac, xid):
    bootp = struct.pack("!BBBBIHH", 1, 1, 6, 0, xid, 0, 0x8000)
 # ciaddr/yiaddr/siaddr/giaddr are each 4 bytes = 16; writing one more field will change chaddr
 # Squeeze out the 16-byte boundary, and the guard parses out the miscellaneous MAC of 00:00:00:00:52:55 and silently drops the packet.
 # (Actual test on 2026-08-17: This bug prevented a lease from being released during the entire flood round).
    bootp += b"\0" * 16 + mac + b"\0" * 10        # chaddr (16)
    bootp += b"\0" * 64 + b"\0" * 128             # sname / file
    bootp += b"\x63\x82\x53\x63"                  # magic cookie
    opts = bytes([53, 1, 1])                       # DHCPDISCOVER
    opts += bytes([61, 7, 1]) + mac                # client-id
    opts += bytes([55, 4, 1, 3, 6, 15])            # param request list
    bootp += opts + bytes([255])
    udp = struct.pack("!HHHH", 68, 67, 8 + len(bootp), 0) + bootp
    total = 20 + len(udp)
    ip = struct.pack("!BBHHHBBH4s4s", 0x45, 0, total, 0, 0, 64, 17, 0,
                     socket.inet_aton("0.0.0.0"), socket.inet_aton("255.255.255.255"))
    ip = ip[:10] + struct.pack("!H", checksum(ip)) + ip[12:]
    return b"\xff" * 6 + mac + b"\x08\x00" + ip + udp

s = socket.socket(socket.AF_PACKET, socket.SOCK_RAW)
s.bind((iface, 0))
for i, m in enumerate(macs):
    mac = bytes.fromhex(m)
    s.send(discover(mac, 0x6B7200 + i))
    print("sent DISCOVER mac=" + ":".join("%02x" % b for b in mac), flush=True)
    time.sleep(0.35)
print(f"done: {len(macs)} discovers sent")
FLOOD
}

kb_ensure_network() {
  if limactl network ls 2>/dev/null | awk 'NR > 1 { print $1 }' | grep -Fxq kube; then
 # The network is already online: fill in the leases.json reserved section (to protect the next daemon restart/lazy startup).
    kb_ensure_dhcp_reservations
    return 0
  fi
  kb_log "creating lima network 'kube' (gateway 192.168.6.1/24)"
 # Write the reserved lease first and then register the network: read leases.json and seed --leases when the guard starts lazily.
 # The static segment/e2e segment is removed from the DHCP pool as soon as it is born. create does not clear prewritten files (confirmed by experiments).
  kb_ensure_dhcp_reservations
  limactl network create kube --gateway 192.168.6.1/24
  kb_log "note: leases.json is not hot-reloaded if VMs were already attached and the daemon is running — run kb_flood_dhcp_reservations <running VM on the kube net> to apply immediately"
}

# ---------------------------------------------------------------------------
#kubeconfig (rule 4: pull + change server/tls-server-name + change context name)
# ---------------------------------------------------------------------------

kb_fetch_kubeconfig() {
  local cluster="$1" cp="$2" kc="$3" api_port="$4" cp_ip="$5" cur cname
  mkdir -p "$(dirname "$kc")"
 # The stdout of limactl shell under non-tty is clean; tr -d '\r' prevents TTY from being mixed in.
  kb_root "$cp" -- cat /etc/kubernetes/admin.conf | tr -d '\r' >"$kc"
  chmod 600 "$kc"
 # The host has no 192.168.6.x route: it can only call the portForward of 127.0.0.1:<api-port>;
 # The certificate SAN is advertise-address, and tls-server-name must be pointed to.
 # Note that what is changed is the existing cluster entry in admin.conf (kubeadm always names it "kubernetes"):
 # `set-cluster <new name>` will only add new entries, the context still refers to the old cluster, and the server will not change.
  cname="$(kubectl --kubeconfig "$kc" config view --minify -o jsonpath='{.clusters[0].name}')"
  [[ -n "$cname" ]] || { echo "cannot find current cluster entry in admin.conf" >&2; return 1; }
  kubectl --kubeconfig "$kc" config set-cluster "$cname" \
    --server="https://127.0.0.1:${api_port}" \
    --tls-server-name="$cp_ip" >/dev/null
  cur="$(kubectl --kubeconfig "$kc" config current-context)"
  if [[ "$cur" != "$cluster" ]]; then
    kubectl --kubeconfig "$kc" config rename-context "$cur" "$cluster" >/dev/null
  fi
  kubectl --kubeconfig "$kc" config use-context "$cluster" >/dev/null
}

kb_cluster_ready() {
  local cluster="$1" kc
  kc="$(kb_kubeconfig_path "$cluster")"
  [[ -s "$kc" ]] || return 1
 # --request-timeout prevents kubectl from being polled due to long hangs when the host has no route.
  kubectl --kubeconfig "$kc" --context "$cluster" --request-timeout=10s \
    cluster-info >/dev/null 2>&1
}

kb_wait_api() {
  local cluster="$1" timeout="${2:-180}" waited=0
  until kb_cluster_ready "$cluster"; do
    if (( waited >= timeout )); then
      echo "api server not ready after ${waited}s: $cluster (kubeconfig $(kb_kubeconfig_path "$cluster"))" >&2
      return 1
    fi
    sleep 5
    waited=$((waited + 5))
  done
}

# ---------------------------------------------------------------------------
# registry static Pod (rule 5)
# ---------------------------------------------------------------------------

kb_registry_pod_spec() {
  cat <<'YAML'
apiVersion: v1
kind: Pod
metadata:
  name: registry
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: registry
      image: registry:3.1.1@sha256:1be55279f18a2fe1a74edf2664cac61c1bea305b7b4642dab412e7affdcb3e33
      ports: [{containerPort: 5000}]
      volumeMounts: [{name: data, mountPath: /var/lib/registry}]
  volumes:
    - name: data
      hostPath: {path: /var/lib/local-registry, type: DirectoryOrCreate}
YAML
}

kb_ensure_registry() {
  local cp="$1" waited=0
  if kb_root "$cp" -- test -f /etc/kubernetes/manifests/registry.yaml; then
    kb_log "registry manifest already present on $cp"
  else
    kb_log "installing registry static pod on $cp (image pull may take a while)"
    kb_registry_pod_spec | kb_root "$cp" -- tee /etc/kubernetes/manifests/registry.yaml >/dev/null
  fi
 # It takes time for kubelet to pull up registry:3 (hostNetwork 0.0.0.0:5000).
  until kb_root "$cp" -- curl -fsS -o /dev/null http://127.0.0.1:5000/v2/ 2>/dev/null; do
    if (( waited >= 180 )); then
      echo "registry not answering on $cp:5000 after ${waited}s; check: kb_root $cp -- kubectl --kubeconfig /etc/kubernetes/admin.conf -n kube-system get pod registry" >&2
      return 1
    fi
    sleep 5
    waited=$((waited + 5))
  done
  kb_log "registry up on $cp:5000"
}

# ---------------------------------------------------------------------------
#hosts.toml image analysis (registry side of rule 6)
# ---------------------------------------------------------------------------

#certs.d only takes effect when the registry config_path of containerd points to it (`containerd
#The config.toml generated by config default` contains an empty string). Idempotent: Skip the value if it is correct, and wait until it is rewritten.
#restart containerd (static pod is automatically pulled back by kubelet, no harm).
kb_wire_containerd_certs_d() {
  local vm="$1" cfg=/etc/containerd/config.toml
  if kb_root "$vm" -- grep -q "config_path = '/etc/containerd/certs.d'" "$cfg"; then
    return 0
  fi
  kb_root "$vm" -- sed -i \
    -e "s|config_path *= *''|config_path = '/etc/containerd/certs.d'|" \
    -e 's|config_path *= *""|config_path = "/etc/containerd/certs.d"|' \
    "$cfg"
  if ! kb_root "$vm" -- grep -q "config_path = '/etc/containerd/certs.d'" "$cfg"; then
    echo "cannot set registry config_path in $vm:$cfg (unexpected format); wire manually" >&2
    kb_root "$vm" -- grep -n 'config_path' "$cfg" >&2 || true
    return 1
  fi
  kb_root "$vm" -- systemctl restart containerd
  kb_log "containerd config_path wired on $vm"
}

kb_ensure_hosts_toml() {
  local cluster="$1" cp_ip toml vm
  cp_ip="$(kb_cluster_ip "$cluster")"
  toml="$(printf 'server = "http://%s:5000"\n[host."http://%s:5000"]\n  capabilities = ["pull", "resolve"]\n' "$cp_ip" "$cp_ip")"
  for vm in $(kb_cluster_vms "$cluster"); do
    kb_root "$vm" -- mkdir -p /etc/containerd/certs.d/registry.convee.local:5000
    printf '%s\n' "$toml" | kb_root "$vm" -- tee /etc/containerd/certs.d/registry.convee.local:5000/hosts.toml >/dev/null
    kb_wire_containerd_certs_d "$vm"
  done
}

# ---------------------------------------------------------------------------
#Image push (rule 6: 127.0.0.0/8 defaults to insecure, prompts to write daemon.json only if failed)
# ---------------------------------------------------------------------------

kb_push_image() {
  local port="$1" img="$2"
  local repo="${img#registry.convee.local:5000/}"
  local out="" tag
 # Main path: host docker directly pushes 127.0.0.1 (this is established when hosts such as Linux/colima share loopback with dockerd;
 # 127.0.0.0/8 defaults to insecure, no daemon.json required).
  tag="127.0.0.1:${port}/${repo}"
  if docker tag "$img" "$tag" 2>/dev/null \
    && out="$(docker push "$tag" 2>&1)"; then
    printf '%s\n' "$out" | tail -1
    return 0
  fi
  kb_log "docker push $tag failed: $(printf '%s\n' "${out:-docker tag failed, no push output}" | tail -1)"
  docker rmi "$tag" >/dev/null 2>&1 || true   # drop the local tag the failed attempt left behind
 # Docker Desktop (macOS): dockerd is in its own VM, 127.0.0.1 is the VM loopback and cannot be touched
 # Host's lima port forwarding (connection refused); host.docker.internal is reachable, but not
 # 127.0.0.0/8 → dockerd forces HTTPS (http: server gave HTTP response to HTTPS client).
 # This path will only work if the insecure entry is explicitly added to daemon.json. Try this once:
  tag="host.docker.internal:${port}/${repo}"
  if docker tag "$img" "$tag" 2>/dev/null \
    && out="$(docker push "$tag" 2>&1)"; then
    printf '%s\n' "$out" | tail -1
    return 0
  fi
  kb_log "docker push $tag failed: $(printf '%s\n' "${out:-docker tag failed, no push output}" | tail -1)"
  docker rmi "$tag" >/dev/null 2>&1 || true
 # Bottom line: skopeo runs in the host process (without dockerd) and directly pushes the plain HTTP of the host loopback.
  if command -v skopeo >/dev/null 2>&1; then
    kb_log "docker push unavailable; falling back to skopeo (docker-daemon -> 127.0.0.1:${port}, plain HTTP)"
    skopeo copy --dest-tls-verify=false "docker-daemon:${img}" "docker://127.0.0.1:${port}/${repo}"
    return $?
  fi
  cat >&2 <<EOF
[kb] push failed (docker cannot push to 127.0.0.1:${port} over plain HTTP). Either fix works:
  1) Install skopeo (macOS: brew install skopeo; Debian/Ubuntu: apt install skopeo;
     Fedora/RHEL: dnf install skopeo) — recommended: the host pushes to loopback
     directly, without touching dockerd or restarting containers.
  2) Add insecure-registries: ["host.docker.internal:${port}"] to dockerd and
     restart Docker — note this restarts all containers. This path mainly targets
     Docker Desktop on macOS (dockerd sits in its own VM and cannot reach the host
     loopback); on Linux the host shares the loopback with dockerd, so the primary
     path above usually just works, and landing here usually has another cause.
EOF
  return 1
}

# ---------------------------------------------------------------------------
#Clean up (rule 7: list e2e-* VMs and orphan disks, delete them only if --yes)
# ---------------------------------------------------------------------------

kb_prune() {
  local yes=0 vms disks name
  if [[ "${1:-}" == "--yes" ]]; then yes=1; fi
 # e2e-* VM: It is a temporary cluster according to the naming convention, and kubeconfig is no longer verified.
  vms="$(limactl list -f '{{.Name}}' 2>/dev/null | grep -E '^e2e-' || true)"
 # Orphan disk: lima disk whose IN-USE-BY is empty.
  disks="$(limactl disk list 2>/dev/null | awk 'NR==1{for(i=1;i<=NF;i++)if($i=="IN-USE-BY")c=i;next} c && $c=="" && NF>0 {print $1}')"
  if [[ -z "$vms" && -z "$disks" ]]; then
    kb_log "prune: nothing to do (no e2e-* vms, no orphaned disks)"
    return 0
  fi
  if (( yes )); then
    for name in $vms; do
      kb_log "prune: deleting vm $name"
      limactl delete -f "$name"
    done
    for name in $disks; do
      kb_log "prune: deleting disk $name"
      limactl disk delete "$name"
    done
  else
    {
      echo "[kb] prune candidates (dry-run):"
      [[ -n "$vms" ]] && printf '  vm:   %s\n' "$vms"
      [[ -n "$disks" ]] && printf '  disk: %s\n' "$disks"
      echo "[kb] re-run with: kb_prune --yes"
    } >&2
  fi
}

#kubeadm preflight hard requirement net.ipv4.ip_forward=1 (Ubuntu cloud image default 0,
#And check both kubeadm init/join). Write /etc/sysctl.d persistence + effective immediately, idempotent and replayable.
kb_ensure_sysctls() {
  local vm="$1"
  if kb_root "$vm" -- sysctl -n net.ipv4.ip_forward | grep -qx 1; then
    return 0
  fi
  kb_log "enabling net.ipv4.ip_forward on $vm"
  printf 'net.ipv4.ip_forward=1\n' | kb_root "$vm" -- tee /etc/sysctl.d/99-kube.conf >/dev/null
  kb_root "$vm" -- sysctl -w net.ipv4.ip_forward=1
}

#kubelet node-ip is nailed to the profile static IP (idempotent: the node-ip is already included in the flags, so it is skipped).
#Why it must be done (2026-08-18 workload plus worker test): on a VM with several network
#interfaces the kubelet picks the default-route interface (for the workload control plane
#that is eth0/192.168.7.x of workload-mgmt) while the kube network (192.168.6.x) is only the
#second interface -- the reported node InternalIP lands on another subnet, so Cilium
#The vxlan tunnel endpoint is not in the cluster network, and the cross-node Pod is directly connected/Service all times out (the same node is not affected,
#Only added nodes are exposed). kubeadm init's --apiserver-advertise-address only pins
#The apiserver certificate SAN does not nail the kubelet self-reported address. After the change is completed, you need to restart kubelet to take effect;
#Cilium relies on node InternalIP to build the tunnel endpoint. After changing it, you need to restart the node cilium pod.
# (Triggered by make bootstrap / manually, not handled here).
kb_ensure_kubelet_node_ip() {
  local vm="$1" ip="$2" flags_file="/var/lib/kubelet/kubeadm-flags.env"
  if kb_root "$vm" -- grep -q -- "--node-ip=${ip}" "$flags_file" 2>/dev/null; then
    return 0
  fi
  kb_log "pinning kubelet node-ip=$ip on $vm"
 # The flags file generated by kubeadm is in the shape of KUBELET_KUBEADM_ARGS="...": merge --node-ip
 # Enter the existing value (remove --node-ip in the original value first to prevent duplication of parameters), and restart kubelet after changing it.
  kb_root "$vm" -- sh -c \
    "old=\$(sed -n 's/^KUBELET_KUBEADM_ARGS=\"\(.*\)\"/\1/p' '$flags_file' 2>/dev/null); \
     cleaned=\$(printf '%s' \"\$old\" | sed 's/--node-ip=[^ ]*//g'); \
     printf 'KUBELET_KUBEADM_ARGS=\"%s --node-ip=$ip\"\n' \"\$cleaned\" > '$flags_file'; \
     systemctl restart kubelet"
}

#Node podCIDR is delivered deterministically. Why it must be done (live actual measurement + upstream source code verification v1.36.1):
#profile current CIDR design svc=10.2xx.128.0/16 ⊂ pod=10.2xx.0.0/16 and the same /16 mask,
#kube-controller-manager RangeAllocator's filterOutServiceRange→Occupy(svc) is in
#When clusterMaskSize == svcMaskSize, take the hidden branch of getBeginningAndEndIndices
#(`clusterMaskSize < maskSize` is not true, begin/end maintains [0, maxCIDRs-1]),
#Occupy the entire pod pool → Nodes can never be allocated podCIDR, Cilium (ipam=kubernetes) is stuck
# "required IPv4 PodCIDR not available" and coredns stays Pending.
#Solution: According to the VM order of the profile, the nth VM (the node name is the guest's actual hostname) is delivered
#<pod base prefix>.n.0/24 (n < 128, does not fall into the .128 half of svc). KCM pairs existing podCIDR
#The nodes are only occupied and not rewritten (actually stuck); after the boundary is removed by the upstream, this function degenerates into a pure no-op.
kb_ensure_node_cidrs() {
  local cluster="$1" kc pod base vm node_name cur cidr idx used
  local grace want t0 node_cidrs have blank
  kc="$(kb_kubeconfig_path "$cluster")"
  pod="$(kb_profile show "$cluster" | sed -n 's/.* pod=\([^ ]*\).*/\1/p')"
  base="${pod%.*.*}"   # e.g. 10.207; shape validation is deferred until a node really is missing a podCIDR (see below)
 # Grace window: wait for KCM to allocate naturally (~6s after init of v1.36.1 healthy netlist on real machine).
 # When there is no window, the pocket patch will run ahead of KCM - the upstream full health will also be triggered every round, covering up the health.
 # Signal, violating the contract of "it will degrade to no-op after the upstream fixes it". KB_KUBEADM_CIDR_GRACE=0 is off.
  grace="${KB_KUBEADM_CIDR_GRACE:-30}"
  want="$(kb_cluster_vms "$cluster" | wc -w)"; want="${want// /}"
  node_cidrs=""
  t0=$SECONDS
  while (( SECONDS - t0 < grace )); do
    node_cidrs="$(kubectl --kubeconfig "$kc" --context "$cluster" --request-timeout=10s \
      get nodes -o jsonpath='{range .items[*]}{.spec.podCIDR}{"\n"}{end}' 2>/dev/null)" || node_cidrs=""
    have="$(printf '%s\n' "$node_cidrs" | grep -c .)" || true
    blank="$(printf '%s\n' "$node_cidrs" | grep -c '^$')" || true
    if (( have >= want && blank == 0 )); then
      break
    fi
    sleep 2
  done
 # Pre-collect occupied /24 of the entire cluster: The allocation order of KCM may not be equal to the VM iteration order, which is required when selecting idx
 # Skip any occupied /24 instead of trusting the idx== position.
  used="$(printf '%s\n' "$node_cidrs" | grep -v '^$' | paste -sd, -)" || true
  for vm in $(kb_cluster_vms "$cluster"); do
    node_name="$(kb_root "$vm" -- hostname | tr -d '\r')"
    if cur="$(kubectl --kubeconfig "$kc" --context "$cluster" --request-timeout=10s \
      get node "$node_name" -o jsonpath='{.spec.podCIDR}' 2>/dev/null)" && [[ -n "$cur" ]]; then
      continue
    fi
 # Only verify the pod CIDR form when there is indeed a node that lacks podCIDR: future form evolution (such as /20) should not
 # Suspend a cluster where all nodes are ready (the backend logic should degenerate into no-op).
    if [[ "$pod" != *.0.0/16 ]]; then
      echo "unexpected pod cidr shape (want x.y.0.0/16): $pod" >&2
      return 1
    fi
    idx=0
    while (( idx < 128 )); do
      cidr="${base}.${idx}.0/24"
      [[ ",$used," == *",${cidr},"* ]] || break
      idx=$((idx + 1))
    done
    if (( idx >= 128 )); then
      echo "podCIDR index overflow (>128 nodes) for $cluster" >&2
      return 1
    fi
    kb_log "assigning podCIDR $cidr to node $node_name ($vm)"
    kubectl --kubeconfig "$kc" --context "$cluster" --request-timeout=10s \
      patch node "$node_name" --type=merge \
      -p "{\"spec\":{\"podCIDR\":\"$cidr\",\"podCIDRs\":[\"$cidr\"]}}" >/dev/null
    used="${used:+$used,}$cidr"
  done
}

#The kubeadm cluster has no built-in StorageClass, CSI driver, or provisioner. Without one,
#PVCs that request storageClassName: standard (or rely on the default class) remain Pending.
#It stays Pending forever (a primary-database StatefulSet and the management workload-home
#volume are both in that position).
#The content is the same as the generic local-path manifest byte by byte (upstream script rancher
#local-path-provisioner v0.0.31 deploy/local-path-storage.yaml, diff = SC renamed
#standard + default class annotation + image digest lock).  Downstream application repositories
#that vendor a byte-identical copy of this manifest must be kept in sync when either side changes.
kb_storage_class_manifest() {
  cat <<'YAML'
apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-service-account
  namespace: local-path-storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: local-path-provisioner-role
  namespace: local-path-storage
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: local-path-provisioner-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "configmaps", "pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: local-path-provisioner-bind
  namespace: local-path-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: local-path-provisioner-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-service-account
    namespace: local-path-storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-path-provisioner-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-path-provisioner-role
subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-service-account
    namespace: local-path-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
  labels:
    app.kubernetes.io/name: local-path-provisioner
    app.kubernetes.io/part-of: infra-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-path-provisioner
  template:
    metadata:
      labels:
        app: local-path-provisioner
    spec:
      serviceAccountName: local-path-provisioner-service-account
      nodeSelector:
        infra.convee.io/node-role: system
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: local-path-provisioner
          image: rancher/local-path-provisioner:v0.0.31@sha256:80496fdeb307541007621959aa13aed41d31db9cd2dc4167c19833e0bfa3878c
          imagePullPolicy: IfNotPresent
          command:
            - local-path-provisioner
            - start
            - --config
            - /etc/config/config.json
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_MOUNT_PATH
              value: /etc/config/
      volumes:
        - name: config-volume
          configMap:
            name: local-path-config
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
    {
            "nodePathMap":[
            {
                    "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                    "paths":["/opt/local-path-provisioner"]
            }
            ]
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
      - name: helper-pod
        image: busybox:1.37.0@sha256:9db7b59979c38555a39def84a31fb98b5296952f9e3afd4f6f11f05b07adfab0
        imagePullPolicy: IfNotPresent
YAML
}

kb_ensure_storage_class() {
  local cluster="$1" kc
  kc="$(kb_kubeconfig_path "$cluster")"
  kb_log "reconciling default StorageClass 'standard' (local-path) on $cluster"
  kb_storage_class_manifest \
    | kubectl --kubeconfig "$kc" --context "$cluster" apply -f - >/dev/null
 # PVC binding needs to wait until the provisioner is ready (image first pull + helper pod are all in this section).
 # Waiting without hard gate: when the control-plane taint of the single VM kubeadm cluster has not been removed provisioner
 # will always be Pending - and the taint removal is the caller (bootstrap.sh create_cluster /
 # workload-kubeadm.sh), timing occurs after this function returns **, just wait for it
 # "Installing SC" and "Picking Spots" are locked and wait for each other. Here we only do best-effort pre-pull and keep logs; real readiness
 # The gate is located at the rollout of the PVC consumer (postgres StatefulSet, etc.).
  if ! kubectl --kubeconfig "$kc" --context "$cluster" -n local-path-storage \
    rollout status deployment/local-path-provisioner --timeout=180s >/dev/null; then
    kb_log "local-path-provisioner not ready yet on $cluster (control-plane taint / image pull); the PVC consumers' rollout will cover it"
  fi
}

# ---------------------------------------------------------------------------
#kb_ensure_cluster: idempotently brings a cluster to Ready (assembly of rules 1-6)
# ---------------------------------------------------------------------------

kb_ensure_cluster() {
  local cluster="$1"
  local show cp cp_ip kc api_port pod_cidr svc_cidr vm w join_cmd
  local -a join_args

  show="$(kb_profile show "$cluster")"
 # There is no comma in the vms= line of a single VM cluster, and the first VM name must also stop on a space/comma.
  cp="$(printf '%s\n' "$show" | sed -n 's/.*vms=\([^, ]*\).*/\1/p')"
  cp_ip="$(printf '%s\n' "$show" | sed -n "s/.*ips=\['\([^']*\)'.*/\1/p")"
  pod_cidr="$(printf '%s\n' "$show" | sed -n 's/.* pod=\([^ ]*\).*/\1/p')"
  svc_cidr="$(printf '%s\n' "$show" | sed -n 's/.* svc=\([^ ]*\).*/\1/p')"
  kc="$(kb_kubeconfig_path "$cluster")"
  api_port="$(kb_api_port "$cluster")"
  if [[ -z "$cp" || -z "$cp_ip" || -z "$pod_cidr" || -z "$svc_cidr" || -z "$api_port" ]] \
    || ! [[ "$cp" =~ ^[A-Za-z0-9][A-Za-z0-9._-]*$ ]]; then
    echo "profile show parse failed for $cluster (cp='$cp'):" >&2
    printf '%s\n' "$show" >&2
    return 1
  fi
  kb_log "cluster $cluster: cp=$cp ip=$cp_ip pod=$pod_cidr svc=$svc_cidr api_port=$api_port kc=$kc"

 # Network pre-construction (must be started before any VM - the interface is connected to the network when the VM is started).
  kb_ensure_network

  for vm in $(kb_cluster_vms "$cluster"); do
    kb_vm_up "$vm"
    kb_ensure_sysctls "$vm"
 # On a VM with several network interfaces the kubelet self-reported IP has to be pinned to
 # the kube-network static IP (see the function comment); otherwise the cross-node vxlan is
 # completely broken once workers are added.  kb_vm_up is idempotent -- a running VM is not
 # restarted -- so changing the flags and restarting the kubelet is the repair path here.
    kb_ensure_kubelet_node_ip "$vm" "$(kb_vm_ip "$cluster" "$vm")"
  done

 # init (idempotent criterion: skip if /etc/kubernetes/admin.conf exists).
  if ! kb_root "$cp" -- test -f /etc/kubernetes/admin.conf; then
    kb_log "kubeadm init on $cp (advertise $cp_ip)"
    kb_root "$cp" -- kubeadm init \
      --kubernetes-version "$KB_KUBEADM_K8S_VERSION" \
      --apiserver-advertise-address "$cp_ip" \
      --pod-network-cidr "$pod_cidr" \
      --service-cidr "$svc_cidr" \
      --upload-certs
  else
    kb_log "kubeadm already initialized on $cp"
  fi

 # kubeconfig: pull + change server/context (idempotent: rewriting each time is harmless).
  kb_fetch_kubeconfig "$cluster" "$cp" "$kc" "$api_port" "$cp_ip"
 # When the VM is restarted for reuse, the apiserver will take tens of seconds to pull up. Please wait before executing subsequent idempotent criteria.
  kb_wait_api "$cluster" 180
  kubectl --kubeconfig "$kc" --context "$cluster" label node \
    -l node-role.kubernetes.io/control-plane \
    infra.convee.io/node-role=system --overwrite >/dev/null

 # join workers (idempotent criterion: skip if /etc/kubernetes/kubelet.conf exists on worker).
  for w in $(kb_cluster_vms "$cluster"); do
    if [[ "$w" == "$cp" ]]; then
      continue
    fi
    if kb_root "$w" -- test -f /etc/kubernetes/kubelet.conf; then
      kb_log "$w already joined"
      continue
    fi
    join_cmd="$(kb_root "$cp" -- kubeadm token create --print-join-command)"
    read -r -a join_args <<<"$join_cmd"
    kb_log "joining $w"
    kb_root "$w" -- ${join_args[@]+"${join_args[@]}"}
  done

 # Node podCIDR (must be before Cilium: ipam=kubernetes, etc. node.podCIDR can be ready).
  kb_ensure_node_cidrs "$cluster"

 # Cilium installation belongs to the cluster lifecycle owned by infra.
 # Use ds/cilium for the criterion (cilium in the chart is DaemonSet; Deployment is called cilium-operator.
 # Check that deploy/cilium will always be NotFound, causing incorrect reinstallation in each round).
  KUBECONFIG="$kc" "$kb_repo_root/scripts/install-cilium-kubeadm.sh" "$cluster"

 # registry + node-side image resolution (both are idempotent).
  kb_ensure_registry "$cp"
  kb_ensure_hosts_toml "$cluster"

 #Default StorageClass required by the workloads' PVCs.
  kb_ensure_storage_class "$cluster"

  kb_log "cluster $cluster ready (kubeconfig=$kc context=$cluster api=https://127.0.0.1:${api_port})"
}
